on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  doSomething:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: ls
    - run: azcopy copy .\WebsiteSourceCode\* '${{secrets.AZURE_STORAGE_CONN_STRING}}'
